config/routes.rb
Rails.application.routes.draw do

  resources :invoices
  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
    end
  end

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root to: "home#dashboard"

  get 'home/index'
  get 'home/dashboard'
  get 'home/calendar'
  get 'home/report'
  get 'home/chart'

  resources :users, only: [:index, :show]
  resources :installments do
    get 'cancel', on: :member
  end
  resources :launches do
    get 'apportionment', on: :member
    resources :installments, only: [:index, :edit, :update]
  end
  resources :categories
  resources :accounts
  resources :cards
  resources :groups do
      get 'dashboard', on: :member
    resources :user_groups do
      get 'enable', on: :member
      get 'disable', on: :member
    end
  end
  resources :goals do
    get 'chart', on: :collection
  end
  resources :notifications

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base

  belongs_to :group
  belongs_to :user

  validates :role, :group, :email, presence: true
  validates :group, uniqueness: { scope: :email }
  validates :email, length: { in: 3..100 }
  validate :validate_email

  enum role: %w(admin launcher viewer)

  def validate_email
    unless email =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      errors.add(:email, "não é um e-mail")
    end
  end

  def search_user
    user = User.find_by(email: self.email)
    self.user = user
  end

  def notify_user
    if self.user.present?
      Notification.create(
        user: self.user,
        title: I18n.t('models.notification.title_user_group'), 
        description: I18n.t('models.notification.description_user_group', group: self.title), 
        icon: 'group' )
    end
  end

end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user_group, only: [:show, :edit, :update, :destroy, :enable, :disable]
  before_action :set_group, only: [:index, :show, :new, :edit, :create, :update, :destroy, :enable, :disable]
  after_action :verify_authorized, except: [:index, :new, :create]

  respond_to :html

  def index
    @user_groups = policy_scope(UserGroup)
    @user_groups = @user_groups.where(group: @group)
    respond_with(@user_groups)
  end

  def show
    respond_with(@user_group)
  end

  def new
    @user_group = @group.user_groups.build
    respond_with(@user_group)
  end

  def edit
  end

  def create
    @user_group = @group.user_groups.build(user_group_params)
    @user_group.search_user
    if @user_group.save and current_user != @user_group.user
      UserGroupMailer.invite_user_to_group(current_user, @user_group).deliver_now!
      @user_group.notify_user
    end
    respond_with(@group, @user_group)
  end

  def update
    @user_group.update(user_group_params)
    respond_with(@group, @user_group)
  end

  def destroy
    @user_group.destroy
    respond_with(@user_group, location: group_user_groups_path(@group))
  end

  def enable
    @user_group.update_attribute(:enabled, true)
    flash[:notice] = t('models.user_group.enabled')
    redirect_to home_dashboard_path
  end

  def disable
    @user_group.update_attribute(:enabled, false)
    flash[:notice] = t('models.user_group.disabled')
    redirect_to home_dashboard_path
  end

  private
    def set_user_group
      @user_group = UserGroup.find(params[:id])
      authorize @user_group
    end

    def user_group_params
      params.require(:user_group).permit(:enabled, :role, :group_id, :email)
    end

    def set_group
      @group = Group.find(params[:group_id])
    end
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_form.html.erb
<div class='row'>
  <div class='col-sm-12'>
    <div class='box bordered-box green-border'>
      <div class='box-header green-background'>
        <div class='title'>
          <%= t('helpers.new') if action_name == 'new' %>
          <%= t('helpers.edit') if action_name == 'edit' %>
        </div>
      </div>
      <div class='box-content box-double-padding'>
        <%= simple_form_for([@group, @user_group], wrapper: :horizontal_form, html: {class: 'form form-horizontal'}) do |f| %>
          <%= f.error_notification %>
          <fieldset>
            <div class='col-sm-8 col-sm-offset-2'>
              <!-- <div class='form-group'> -->
                <%#= f.input :role, collection: options_for_enum(UserGroup, :role, @user_group), include_blank: false %>
              <!-- </div> -->
              <div class='col-sm-offset-3'>
                <%= @user_group.user.name if @user_group.persisted? %>
              </div>
              <div class='form-group'>
                <%= f.input :email, disabled: @user_group.persisted? %>
              </div>
              <!-- <div class='form-group'> -->
                <%#= f.input :enabled %>
              <!-- </div> -->
            </div>
          </fieldset>
          <hr class='hr-normal'>
          
          <div class='row'>
            <div class='col-sm-7 col-sm-offset-5'>
              <%= f.button :submit, t('models.user_group.invite'), class: 'btn-lg btn-success' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user_groups/_header.html.erb
<div class='page-header page-header-with-buttons'>
  <h1 class='pull-left'>
    <i class='icon-upload'></i>
    <span><%= t('activerecord.models.user_group.other') %></span>
  </h1>
  <!-- <div class='pull-right'>
    <div class='btn-group'>
      <a class="btn btn-white hidden-xs" href="#">Last month</a>
      <a class="btn btn-white" href="#">Last week</a>
      <a class="btn btn-white " href="#">Today</a>
            <a class="btn btn-white" id="daterange" href="#"><i class='icon-calendar'></i>
      <span>Custom</span>
      <b class='caret'></b>
      </a>
    </div>
  </div> -->
</div>

app/views/user_groups/edit.html.erb
<%= render 'header' %>
<%= render 'form' %>

<%= link_to t('helpers.links.show'), [@group, @user_group] %> |
<%= link_to t('helpers.links.back'), group_user_groups_path(@group) %>

app/views/user_groups/index.html.erb
<%= render 'header' %>

<div class='box bordered-box green-border' style='margin-bottom:0;'>
  <div class='box-header green-background'>
    <div class='title'>
      <%= t('helpers.index') %>
    </div>
  </div>
  <div class='box-content box-no-padding'>
    <div class='responsive-table'>
      <div class='scrollable-area'>
        <table class='table' style='margin-bottom:0;'>
          <thead>
            <tr>
              <th>
                <%= UserGroup.human_attribute_name("group") %>
              </th>
              <th>
                <%= UserGroup.human_attribute_name("user") %>
              </th>
              <th>
                <%= UserGroup.human_attribute_name("role") %>
              </th>
              <th>
                <%= UserGroup.human_attribute_name("enabled") %>
              </th>
              <th colspan="3">
                <%= t('helpers.actions') %>
              </th>
            </tr>
          </thead>

          <tbody>
            <% @user_groups.each do |user_group| %>
              <tr>
                <td><%= user_group.group.title %></td>
                <td><%= user_group.user.try(:name) %></td>
                <td><%= t("activerecord.attributes.user_group.roles.#{user_group.role}") %></td>
                <td><%= human_boolean(user_group.enabled) %></td>
                <td><%= link_to '<i class="icon-search"></i>'.html_safe, [@group, user_group] %></td>
                <td><%= link_to '<i class="icon-edit"></i>'.html_safe, edit_group_user_group_path(@group, user_group) %></td>
                <td><%= link_to '<i class="icon-unlock"></i>'.html_safe, enable_group_user_group_url(@group, user_group) %></td>
                <td><%= link_to '<i class="icon-lock"></i>'.html_safe, disable_group_user_group_url(@group, user_group) %></td>
                <td><%= link_to '<i class="icon-trash"></i>'.html_safe, [@group, user_group], method: :delete, data: { confirm: t('helpers.are_you_sure') } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<br>
<%= link_to t('models.user_group.new_member'), new_group_user_group_path(@group) %>

app/views/user_groups/new.html.erb
<%= render 'header' %>
<%= render 'form' %>

<%= link_to t('helpers.links.back'), group_user_groups_path(@group) %>

app/views/user_groups/show.html.erb
<%= render 'header' %>

<div class='row'>
  <div class='col-sm-12'>
    <div class='box bordered-box green-border'>
      <div class='box-header green-background'>
        <div class='title'>
          <%= t('helpers.show') %>
        </div>
      </div>
      <div class='box-content box-double-padding'>
        <p>
          <strong><%= UserGroup.human_attribute_name("group") %>:</strong>
          <%= @user_group.group.title %>
        </p>

        <p>
          <strong><%= UserGroup.human_attribute_name("user") %>:</strong>
          <%= @user_group.user.try(:name) %>
        </p>

        <p>
          <strong><%= UserGroup.human_attribute_name("role") %>:</strong>
          <%= t("activerecord.attributes.user_group.roles.#{@user_group.role}") %>
        </p>
        <p>
          <strong><%= UserGroup.human_attribute_name("enabled") %>:</strong>
          <%= human_boolean(@user_group.enabled) %>
        </p>
      </div>
    </div>
  </div>
</div>

<%= link_to t('helpers.titles.edit', model: t("activerecord.models.user_group.one")), edit_group_user_group_path(@group, @user_group) %> |
<%= link_to t('helpers.links.back'), group_user_groups_path(@group) %>