config/routes.rb
Rails.application.routes.draw do

  resources :invoices
  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
    end
  end

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root to: "home#dashboard"

  get 'home/index'
  get 'home/dashboard'
  get 'home/calendar'
  get 'home/report'
  get 'home/chart'

  resources :users, only: [:index, :show]
  resources :installments do
    get 'cancel', on: :member
  end
  resources :launches do
    get 'apportionment', on: :member
    resources :installments, only: [:index, :edit, :update]
  end
  resources :categories
  resources :accounts
  resources :cards
  resources :groups do
      get 'dashboard', on: :member
    resources :user_groups do
      get 'enable', on: :member
      get 'disable', on: :member
    end
  end
  resources :goals do
    get 'chart', on: :collection
  end
  resources :notifications

end

app/models/group.rb
class Group < ActiveRecord::Base

  has_many :user_groups, dependent: :destroy
  has_many :users, through: :user_groups
  has_many :launches
  has_many :installments
  belongs_to :user

  validates :title, presence: true, uniqueness: { scope: :user_id }, length: { in: 2..100 }
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy, :dashboard]
  after_action :verify_authorized, except: [:index, :new, :create, :dashboard]
  before_action :get_period_installments, only: [:dashboard]

  respond_to :html, :json, :js

  def index
    @groups = policy_scope(Group)
    respond_with(@groups)
  end

  def show
    respond_with(@group)
  end

  def new
    @group = Group.new
    respond_with(@group)
  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    @group.user_groups.build(user: current_user, email: current_user.email, role: 'admin', enabled: true)
    @group.save
    if params[:group][:modal] == 'launch'
      redirect_to new_launch_path
    else
      respond_with(@group, location: group_user_groups_path(@group))
    end
  end

  def update
    @group.update(group_params)
    respond_with(@group, location: group_user_groups_path(@group))
  end

  def destroy
    @group.destroy
    respond_with(@group)
  end

  def dashboard
    Launch.generate_recurrence_launches(current_user, @search_period)

    @installments = @group.installments
    @installments = @installments.where(date: @start_date..@end_date).order(:date)

    respond_with(@installments) do |format|
      format.csv { send_data @installments.to_csv, filename: "installments-#{Date.today}.csv" }
    end
  end

  private
    def set_group
      @group = Group.find(params[:id])
      authorize @group
    end

    def group_params
      params.require(:group).permit(:title, :description)
    end

    def get_period_installments
      @search_period_type = params[:search_period_type] || 'month'
      @search_period = params[:search_period].try(:to_time) || DateTime.now
      @start_date = params[:start_date].try(:to_time) || @search_period.send("beginning_of_#{@search_period_type}")
      @end_date = params[:end_date].try(:to_time) || @search_period.send("end_of_#{@search_period_type}")
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class='row'>
  <div class='col-sm-12'>
    <div class='box bordered-box green-border'>
      <div class='box-header green-background'>
        <div class='title'>
          <%= t('helpers.new') if action_name == 'new' %>
          <%= t('helpers.edit') if action_name == 'edit' %>
        </div>
      </div>
      <div class='box-content box-double-padding'>
	      <%= simple_form_for(@group, wrapper: :horizontal_form, html: {class: 'form form-horizontal'}) do |f| %>
          <%= f.error_notification %>
          <fieldset>
            <div class='col-sm-8 col-sm-offset-2'>
              <div class='form-group'>
                <%= f.input :title %>
              </div>
              <div class='form-group'>
                <%= f.input :description %>
              </div>
            </div>
          </fieldset>
          <hr class='hr-normal'>
          
          <div class='row'>
            <div class='col-sm-7 col-sm-offset-5'>
              <%= f.button :submit, class: 'btn-lg btn-success' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/_form_modal.html.erb
<div class="modal fade" id="groups_form_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <div style='font-size:18px'>
            <i class='icon-usd'></i>
            <span><%= t('helpers.new') %> <%= t('activerecord.models.group.one') %></span>
          </div>
      </div>
      <div class="modal-body">
        <div class="container">
          <%= simple_form_for(Group.new, wrapper: :horizontal_form, html: {class: 'form form-horizontal'}) do |f| %>
            <%= f.error_notification %>
            <fieldset>
              <div class='col-sm-8 col-sm-offset-2'>
                <div class='form-group'>
                  <%= f.input :title %>
                </div>
                <div class='form-group'>
                  <%= f.input :description %>
                </div>
              </div>
            </fieldset> 
            <%= f.hidden_field :modal, value: :launch %>
       </div>
      </div>
      <div class="modal-footer">
            <%= f.button :submit, class: 'btn-lg btn-success submit_modal', data: {form_id: '#new_group' } %>
          <% end %> 
      </div>
    </div>
  </div>
</div>

app/views/groups/_header.html.erb
<div class='page-header page-header-with-buttons'>
  <h1 class='pull-left'>
    <i class='icon-user'></i>
    <span>
      <%= t('activerecord.models.group.other') %>
      <% if action_name.eql?('dashboard') %>
        - <%= @group.title %>
      <% end %>
    </span>
  </h1>
</div>

app/views/groups/_list_dashboard.html.erb
<div class='box'>
  <div class='box-header'>
    <div class='title'>
      <i class='icon-usd'></i>
      <%= t('activerecord.models.launch.other') %>
    </div>
    <div class='actions'>
        <%= link_to "<i class='icon-file-text'></i>".html_safe, dashboard_group_path(@group, start_date: @start_date, end_date: @end_date, format: :csv), class: 'btn btn-primary  ' %>
        <%= link_to "<i class='icon-plus'></i>".html_safe, new_launch_path, class: 'btn btn-success  ' %>
    </div>
  </div>
  <div class='box-content'>
    <% if @installments.present? %>
      <% @installments.each do |installment| %>
        <div class='list_installment_wrapper'>
          <i class="<%= installment.income? ? 'icon-arrow-up text-green' : 'icon-arrow-down text-red' %> launch_type_icon hidden-xs"></i>
          <div class='col-sm-4 col-xs-4'>
            <h4><%= format_title_recurrence(installment) %></h4>
            <h6 style="color: <%= installment.category.try(:color) %>"><%= installment.category.try(:title) %></h6>  
          </div>
          <div class='col-sm-4 col-xs-4'>
            <h4><%= installment.user.name %></h4>
          </div>
          <div class='col-sm-4 col-xs-4'>
            <h4 class='text-right <%= installment.income? ? 'text-green' : 'text-red' %>'><%= number_to_currency(installment.value) %></h4>
            <h6 class='text-right'><%= l(installment.date, format: :date_picker) %></h6>
          </div>
          <i class="<%= installment.paid? ? 'icon-thumbs-up-alt text-green' : 'icon-thumbs-down-alt text-red' %> paid_icon" title="<%= installment.paid? ? t("models.installment.#{installment.launch_type}.paid") : t("models.installment.#{installment.launch_type}.not_paid") %>"></i>
        </div>
        <div class='clearfix'></div>
        <hr class='dashboard-hr-account'></hr>
      <% end %>
      <% sum_of_installments = Installment.sum_of_values(@installments) %>
      <h4 class='text-right <%= sum_of_installments > 0 ? 'text-green' : 'text-red' %>'><%= number_to_currency(sum_of_installments) %></h4>
    <% else %>
      Não há lançamentos nesse período
    <% end %>
  </div>
</div>

app/views/groups/_period_navigator.html.erb
<div class="previous_date" data-value="<%= @start_date %>"></div>
<div class="next_date" data-value="<%= @end_date %>"></div>

<nav class='text-center'>
  <div class='btn-group'>
    <% if @search_period_type != 'period' %>
      <%= link_to "<i class='icon-chevron-left'></i>".html_safe, '#', class: 'btn btn-success btn-md previous search_period_link', data: { url: dashboard_group_path(@group), period_type: @search_period_type, search_period: @search_period - 1.send("#{@search_period_type}"), context: 'navigation' } %>
    <% end %>
    <div class='btn-group dropdown'>
      <button class='btn btn-success btn-md dropdown-toggle' data-delay='100' data-hover='dropdown' data-toggle='dropdown'>
        <%= date_format %>
        <span class='caret'></span>
      </button>
      <ul class='dropdown-menu'>
        <li>
          <%= link_to t('datetime.prompts.day'), '#', class: 'search_period_link', data: { url: dashboard_group_path(@group), period_type: 'day', context: 'default-period' } %>
        </li>
        <li>
          <%= link_to t('datetime.prompts.week'), '#', class: 'search_period_link', data: { url: dashboard_group_path(@group), period_type: 'week', context: 'default-period' } %>
        </li>
        <li>
          <%= link_to t('datetime.prompts.month'), '#', class: 'search_period_link', data: { url: dashboard_group_path(@group), period_type: 'month', context: 'default-period' } %>
        </li>
        <li>
          <%= link_to 'Por período', "#", data: {toggle: 'modal', target: '#search_period_modal'} %>
        </li>
      </ul>
    </div>
    <% if @search_period_type != 'period' %>
      <%= link_to "<i class='icon-chevron-right'></i>".html_safe, "#", class: 'btn btn-success btn-md next search_period_link', data: { url: dashboard_group_path(@group), period_type: @search_period_type, search_period: @search_period + 1.send("#{@search_period_type}"), context: 'navigation' } %>
     <% end %>
     <i class="icon-3x icon-spinner icon-spin search_loading"></i>
  </div>
</nav>

app/views/groups/_search_period_modal.html.erb
<div class="modal fade" id="search_period_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= t('breadcrumbs.pages.search_by_period') %></h4>
      </div>
      <div class="modal-body">
        <div class="container">
          <div class='col-md-5'>
            <div class="form-group">
              <div class='input-group date' id='datetimepicker_from'>
                <input type='text' class="form-control" />
                <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
                </span>
              </div>
            </div>
          </div>
          <div class='col-md-5'>
            <div class="form-group">
              <div class='input-group date' id='datetimepicker_to'>
                <input type='text' class="form-control" />
                <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= link_to t('helpers.links.search'), '#', class: 'btn btn-success search_period_link', data: { url: dashboard_group_path(@group), period_type: 'period', context: 'period-chosen' } %>
      </div>
    </div>
  </div>
</div>

app/views/groups/dashboard.html.erb
<%= render 'header' %>

<div id='period_navigator_dashboard'>
  <%= render 'period_navigator' %>
</div>

<%= render 'search_period_modal' %>

<div class='row'>
  <div class='col-sm-12' id='installments_list_dashboard'>
    <%= render 'list_dashboard' %>
  </div>

    <div class='col-sm-12 no_launches' style='display:none;'>
      <div class='box'>
        <div class='box-content'>
          <i class='icon-3x icon-remove'></i>
          <h4><%= t('breadcrumbs.pages.no_launches') %></h4>
        </div>
      </div>
    </div>

</div>

app/views/groups/dashboard.js.erb
$('div#period_navigator_dashboard').html('<%= escape_javascript( render(partial: "groups/period_navigator") ) %>');
<% if @installments.any? %>
  $('div.no_launches').hide();
  $('div#installments_list_dashboard').html('<%= escape_javascript( render(partial: "groups/list_dashboard") ) %>');
<% else %>
  $('div.no_launches').show();
  $('div#installments_list_dashboard').html("");
<% end %>

app/views/groups/edit.html.erb
<%= render 'header' %>

<%= render 'form' %>

<%= link_to t('helpers.links.show'), @group %> |
<%= link_to t('helpers.links.back'), groups_path %>

app/views/groups/index.html.erb
<%= render 'header' %>

<div class='box bordered-box green-border' style='margin-bottom:0;'>
  <div class='box-header green-background'>
    <div class='title'>
      <%= t('helpers.index') %>
    </div>
  </div>
  <div class='box-content box-no-padding'>
    <div class='responsive-table'>
      <div class='scrollable-area'>
        <table class='table' style='margin-bottom:0;'>
          <thead>
            <tr>
              <th>
                <%= Group.human_attribute_name("title") %>
              </th>
              <th>
                <%= Group.human_attribute_name("user") %>
              </th>
              <th colspan="3">
                <%= t('helpers.actions') %>
              </th>
            </tr>
          </thead>

          <tbody>
            <% @groups.each do |group| %>
              <tr>
                <td><%= group.title %></td>
                <td><%= group.user.name %></td>
                <td><%= link_to '<i class="icon-dollar"></i>'.html_safe, dashboard_group_path(group) %></td>
                <td><%= link_to '<i class="icon-search"></i>'.html_safe, group_user_groups_path(group) %></td>
                <td><%= link_to '<i class="icon-edit"></i>'.html_safe, edit_group_path(group) %></td>
                <td><%= link_to '<i class="icon-trash"></i>'.html_safe, group, method: :delete, data: { confirm: t('helpers.are_you_sure') } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<br>
<%= link_to t('helpers.titles.new', model: t("activerecord.models.group.one")), new_group_path %>

app/views/groups/new.html.erb
<%= render 'header' %>
<%= render 'form' %>

<%= link_to t('helpers.links.back'), groups_path %>

app/views/groups/show.html.erb
<%= render 'header' %>

<div class='row'>
  <div class='col-sm-12'>
    <div class='box bordered-box green-border'>
      <div class='box-header green-background'>
        <div class='title'>
          <%= t('helpers.show') %>
        </div>
      </div>
      <div class='box-content box-double-padding'>
				<p>
				  <strong><%= Group.human_attribute_name("group") %>:</strong>
				  <%= @group.title %>
				</p>

				<p>
				  <strong><%= Group.human_attribute_name("description") %>:</strong>
				  <%= @group.description %>
				</p>

				<p>
				  <strong><%= Group.human_attribute_name("user") %>:</strong>
				  <%= @group.user.name %>
				</p>
			</div>
		</div>
	</div>
</div>

<%= link_to t('helpers.titles.edit', model: t("activerecord.models.group.one")), edit_group_path(@group) %> |
<%= link_to t('helpers.links.back'), groups_path %>