config/routes.rb
Rails.application.routes.draw do

  resources :invoices
  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
    end
  end

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root to: "home#dashboard"

  get 'home/index'
  get 'home/dashboard'
  get 'home/calendar'
  get 'home/report'
  get 'home/chart'

  resources :users, only: [:index, :show]
  resources :installments do
    get 'cancel', on: :member
  end
  resources :launches do
    get 'apportionment', on: :member
    resources :installments, only: [:index, :edit, :update]
  end
  resources :categories
  resources :accounts
  resources :cards
  resources :groups do
      get 'dashboard', on: :member
    resources :user_groups do
      get 'enable', on: :member
      get 'disable', on: :member
    end
  end
  resources :goals do
    get 'chart', on: :collection
  end
  resources :notifications

end

app/models/installment.rb
class Installment < ActiveRecord::Base

  include Paperclip::Glue

  belongs_to :launch
  belongs_to :installmentable, polymorphic: true
  belongs_to :category
  belongs_to :user
  belongs_to :group
  belongs_to :parent_launch_group, class_name: "Launch"

  validates :value, :date, :number_installment, :launch, :user, presence: true
  validates :value, numericality: true
  validates :number_installment, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validate :validate_mandatory_updates_group

  has_attached_file :proof, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment :proof, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

  enum launch_type: %w(expense income)
  enum update_options: %w(only_this update_future all_update)
  enum cancel_options: %w(cancel_this cancel_future cancel_all)

  attr_accessor :update_option, :cancel_option

  def validate_mandatory_updates_group
    if paid.eql?(true) and category.blank? and global_installmentable.blank?
      errors.add(:category, I18n.t('errors.messages.cant_be_blank'))
      errors.add(:global_installmentable, I18n.t('errors.messages.cant_be_blank'))
    end
  end

  def value= value
    if value =~ /^R\$ ([\d.,]+)$/
      write_attribute :value, $1.gsub('.', '').gsub(',', '.').to_d
    else
      write_attribute :value, value
    end
  end

  def global_installmentable
    self.installmentable.to_global_id if self.installmentable.present?
  end

  def global_installmentable=(installmentable)
    self.installmentable = GlobalID::Locator.locate installmentable
  end

  def update_parent_launch
    launch = self.group.present? ? self.parent_launch_group : self.launch
    launch.title = self.title
    launch.description = self.description
    launch.value = self.value
    launch.date = self.date
    launch.launchable = self.installmentable
    launch.launch_type = self.launch_type
    launch.category = self.category
    launch.save
  end

  def update_installments(option, user)
    self.search_installments_to_update(option, user).each do |installment|
      date_installment = installment.date
      installment.populate_installment(self.user, date_installment)
      date_installment = launch.current_date_installment(date_installment)
    end
  end

  def search_installments_to_update(option, user)
    if option.eql?('update_future')
      self.search_greater_than_installment(user)
    elsif option.eql?('all_update')
      self.search_current_intallments(user)
    end
  end

  def search_current_intallments(user)
    self.launch.installments.where(user: user).order(:number_installment)
  end

  def search_greater_than_installment(user)
    self.search_current_intallments(user).where("number_installment >= ?", self.number_installment)
  end

  def populate_installment(user, date_installment, index=nil)
    launch = self.group.present? ? self.parent_launch_group : self.launch
    value = self.persisted? ? launch.value : launch.calculate_user_value

    self.title = launch.title
    self.description = launch.description
    self.value = value
    self.date = date_installment
    self.launch_type = launch.launch_type
    self.number_installment ||= index
    
    if user.eql?(launch.user)
      self.paid = launch.date.eql?(date_installment) ? launch.paid : false
      self.installmentable = launch.launchable
      self.category = launch.category
    end

    self.user = user
    self.group = launch.group
    self.save
  end
  
  def self.sum_of_values(installments)
    - installments.where(launch_type: 0).sum(:value) + installments.where(launch_type: 1).sum(:value)
  end

  def self.to_csv
    attributes = %w{user title description value date paid category}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |inst|
        csv << [inst.user.name, inst.title, inst.description, inst.value, inst.date, inst.paid, inst.category.try(:title)]
      end
    end
  end

  def self.notify_user_to_installment_due
    Installment.installment_due.each do |installment|
      installment.notify_user
      UserMailer.notify_user_to_installment_due(installment).deliver_now!
    end
  end

  def self.installment_due
    Installment.where(launch_type: 'expense', paid: false, date: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
  end

  def notify_user
    Notification.create(
      user: self.user,
      title: I18n.t('models.notification.title_installment'), 
      description: I18n.t('models.notification.description_installment', title: self.title, value: ActionController::Base.helpers.number_to_currency(self.value)), 
      icon: 'money' )
  end

  def self.search(options = {})
    scope = all
    scope = scope.where(date: (options[:start_date].to_datetime)..(options[:end_date].to_datetime)) if options[:start_date].present? and options[:end_date].present?
    scope = scope.where("title like ?", "%#{options[:title]}%") if options[:title].present?
    scope = scope.where(category_id: options[:category_id]) if options[:category_id].present?
    scope = scope.where(group_id: options[:group_id]) if options[:group_id].present?
    scope = scope.where(installmentable_id: options[:card_id], installmentable_type: 'Card') if options[:card_id].present?
    scope = scope.where(installmentable_id: options[:account_id], installmentable_type: 'Account') if options[:account_id].present?

    if options[:expense].present? and options[:income].present?
      scope = scope
    elsif options[:expense].present?
      scope = scope.where(launch_type: 0)
    elsif options[:income].present?
      scope = scope.where(launch_type: 1)
    end
    
    scope
  end

end

app/controllers/installments_controller.rb
class InstallmentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_installment, only: [:show, :edit, :update, :destroy, :cancel]
  before_action :set_launch, only: [:index]
  after_action :verify_authorized, except: [:index, :new, :create]

  respond_to :html, :js, :json

  def index
    @installments = policy_scope(Installment)
    @installments = @installments.where(launch: @launch)
    respond_with(@installments)
  end

  def show
    respond_with(@installment)
  end

  def new
    @installment = Installment.new
    respond_with(@installment)
  end

  def edit
  end

  def create
    @installment = Installment.new(installment_params)
    @installment.save
    update_accounts_and_cards
    respond_with(@installment)
  end

  def update
    @old_installment = Installment.new(@installment.attributes)
    @installment.update(installment_params)

    if installment_params[:update_option] != 'only_this'
      @installment.update_parent_launch
      @installment.update_installments(installment_params[:update_option], current_user) 
    end
    update_accounts_and_cards
    respond_with(@installment, location: home_dashboard_path)
  end

  def destroy
    if params[:cancel_this].present?
      @old_installment = Installment.new(@installment.attributes)
      @installment.destroy
    else
      cancel_option = installment_params[:cancel_option] 
      launch = @installment.launch
      if cancel_option.eql?('cancel_this') or cancel_option.blank?
        @old_installment = Installment.new(@installment.attributes)
        @installment.destroy
      elsif cancel_option.eql?('cancel_future')
        launch.update_attributes(enabled: false)
        launch.installments.where("date >= ?", @installment.date).destroy_all
      elsif cancel_option.eql?('cancel_all')
        launch.destroy
      end
    end
    update_accounts_and_cards
    respond_with(@installment, location: home_dashboard_path)
  end

  def cancel
    respond_with(@installment)
  end


  private
    def set_installment
      @installment = Installment.find(params[:id])
      authorize @installment
    end

    def installment_params
      params.require(:installment).permit(:title, :description, :value, :date, :paid, :launch_type, :category_id, :global_installmentable, :update_option, 
        :cancel_option, :group_id, :proof)
    end

    def set_launch
      @launch = Launch.find(params[:launch_id])
    end

    def update_accounts_and_cards
      if @installment.installmentable_type == 'Account'
        @installment.installmentable.update_account(@installment, @old_installment, action_name)
      else
        @installment.installmentable.update_card(@installment, @old_installment, action_name)
      end
    end
end

app/helpers/installments_helper.rb
module InstallmentsHelper

	def format_title_recurrence(installment)
		if installment.launch.recurrence?
			"#{installment.title} - #{t("activerecord.attributes.launch.recurrence_types.#{installment.launch.recurrence_type}")}"
		elsif installment.launch.installments?
			"#{installment.title} #{installment.number_installment}/#{installment.launch.amount_installment}"
    else
      installment.title
		end
	end

end

app/views/installments/_cancel_options.html.erb
<div class='box-content box-double-padding'>
  <%= simple_form_for(@installment, method: :delete, wrapper: :horizontal_form, html: {class: 'form form-horizontal'}) do |f| %>
    <%= f.error_notification %>
    <fieldset>
      <div class='col-sm-8 col-sm-offset-2'>
        <div class='form-group'>
          <%= f.input :cancel_option, collection: options_for_enum(Installment, :cancel_option, @installment), checked: :cancel_this, as: :radio_buttons %>
        </div>
      </div>
    </fieldset>
    <hr class='hr-normal'>
    
    <div class='row'>
      <div class='col-sm-7 col-sm-offset-5'>
        <%= f.submit t('helpers.links.cancel'), class: 'btn-lg btn-danger' %>
      </div>
    </div>
  <% end %>
</div>

app/views/installments/_form.html.erb
<div class='row'>
  <div class='col-sm-12'>
    <div class='box bordered-box green-border'>
      <div class='box-header green-background'>
        <div class='title'>
          <%= t('helpers.new') if action_name == 'new' %>
          <%= t('helpers.edit') if action_name == 'edit' %>
        </div>
      </div>
      <div class='box-content box-double-padding'>
        <%= simple_form_for(@installment, wrapper: :horizontal_form, html: {multipart: true, class: 'form form-horizontal'}) do |f| %>
          <%= f.error_notification %>
          <fieldset>
            <div class='col-sm-8 col-sm-offset-2'>
              <div class='form-group'>
                <%= f.input :title %>
              </div>
              <div class='form-group'>
                <%= f.input :description %>
              </div>
              <div class='form-group'>
                <%= f.input :value, as: :string, input_html: {class: 'format_value'} %>
                <label class='paid_input_icon_label'>
                  <i class='icon-2x <%= @installment.paid? ? 'icon-thumbs-up-alt text-green' : 'icon-thumbs-down-alt text-red' %> paid_input_icon'title='<%= t('breadcrumbs.pages.click_to_mark_paid') %>' data-paid='not_paid' data-title-paid='<%= t('breadcrumbs.pages.click_to_mark_paid') %>' data-title-not-paid='<%= t('breadcrumbs.pages.click_to_mark_not_paid') %>' ></i>
                  <%= f.input :paid, wrapper_html: {style: "display:none;"} %>
                </label>
              </div>
              <div class='form-group'>
                <%= f.input :date do %>
                  <div class='datepicker_button input-group'>
                    <%= f.input_field :date, as: :datepicker, class: 'form-control', data: { format: 'dd/mm/yyyy' } %>
                    <span class='input-group-addon'>
                      <i class='icon-calendar'></i>
                    </span>
                  </div>
                <% end %>
              </div>
              <!-- <div class='form-group'> -->
                <%#= f.input :paid %>
              <!-- </div> -->
              <div class='form-group'>
                <%= f.input :global_installmentable, as: :grouped_select, collection: [policy_scope(Account), policy_scope(Card)], group_method: :all, value_method: :to_global_id, group_label_method: :human_model_name, include_blank: false %>
              </div>
              <div class='form-group'>
                <%= f.input :launch_type, collection: options_for_enum(Launch, :launch_type, @launch), include_blank: false %>
              </div>
              <div class='form-group'>
                <%= f.association :category, collection: policy_scope(Category), include_blank: false %>
              </div>
              <div class='form-group'>
                <%= f.input :proof, as: :file %>
              </div>
              <div class='form-group'>
                <%= f.input :update_option, collection: options_for_enum(Installment, :update_option, @installment), checked: :only_this, as: :radio_buttons %>
              </div>
            </div>
          </fieldset>
          <hr class='hr-normal'>
          
          <div class='row'>
            <div class='col-sm-7 col-sm-offset-5'>
              <%= f.button :submit, class: 'btn-lg btn-success' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/installments/_header.html.erb
<div class='page-header page-header-with-buttons'>
  <h1 class='pull-left'>
    <i class='icon-dashboard'></i>
    <span><%= t('activerecord.models.installment.other') %></span>
  </h1>
</div>

app/views/installments/_list.html.erb
<div class='box bordered-box green-border' style='margin-bottom:0;'>
  <div class='box-header green-background'>
    <div class='title'>
      <%= t('helpers.index') %>
    </div>
  </div>
  <div class='box-content box-no-padding'>
    <div class='responsive-table'>
      <div class='scrollable-area'>
        <table class='table' style='margin-bottom:0;'>
          <thead>
            <tr>
              <th>
                <%= Installment.human_attribute_name("title") %>
              </th>
              <th>
                <%= Installment.human_attribute_name("value") %>
              </th>
              <th>
                <%= Installment.human_attribute_name("date") %>
              </th>
              <th>
                <%= Installment.human_attribute_name("paid") %>
              </th>
              <th>
                <%= Installment.human_attribute_name("category") %>
              </th>
              <th colspan="3">
                <%= t('helpers.actions') %>
              </th>
            </tr>
          </thead>

          <tbody>
            <% @installments.each do |installment| %>
              <tr>
                <td><%= format_title_recurrence(installment) %></td>
                <td><%= number_to_currency(installment.value) %></td>
                <td><%= l(installment.date, format: :date_picker) %></td>
                <td><%= human_boolean(installment.paid) %></td>
                <td><span style="background-color:<%= installment.category.color %>;">&nbsp;&nbsp;&nbsp;&nbsp;</span>&nbsp;<%= installment.category.title %></td>
                <td><%= link_to '<i class="icon-search"></i>'.html_safe, installment %></td>
                <td><%= link_to '<i class="icon-edit"></i>'.html_safe, edit_installment_path(installment) %></td>
                <td>
                  <% if installment.launch.not_recurrence? %>
                    <%= link_to '<i class="icon-trash"></i>'.html_safe, installment_path(installment, cancel_this: true), method: :delete, data: { confirm: t('helpers.are_you_sure') } %>
                  <% else %>
                    <%= link_to '<i class="icon-trash"></i>'.html_safe, cancel_installment_path(installment), remote: true %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/installments/_list_dashboard.html.erb
<div class='box'>
  <div class='box-header'>
    <div class='title'>
      <i class='icon-usd'></i>
      <%= t('activerecord.models.launch.other') %>
    </div>
    <div class='actions'>
        <%= link_to "<i class='icon-file-text'></i>".html_safe, home_dashboard_path(start_date: @start_date, end_date: @end_date, format: :csv), class: 'btn btn-primary' %>
        <%= link_to "<i class='icon-plus'></i>".html_safe, new_launch_path, class: 'btn btn-success' %>
    </div>
  </div>
  <div class='box-content'>
    <% if @installments.present? %>
      <% @installments.each do |installment| %>
        <%= link_to installment do %>
          <div class='list_installment_wrapper'>
            <i class="<%= installment.income? ? 'icon-arrow-up text-green' : 'icon-arrow-down text-red' %> launch_type_icon hidden-xs"></i>
            <div class='col-sm-8 col-xs-6'>
              <h4><%= format_title_recurrence(installment) %></h4>
              <h6 style="color: <%= installment.category.try(:color) %>"><%= installment.category.try(:title) %></h6>  
            </div>
            <div class='col-sm-4 col-xs-6'>
              <h4 class='text-right <%= installment.income? ? 'text-green' : 'text-red' %>'><%= number_to_currency(installment.value) %></h4>
              <h6 class='text-right'><%= l(installment.date, format: :date_picker) %></h6>
            </div>
            <i class="<%= installment.paid? ? 'icon-thumbs-up-alt text-green' : 'icon-thumbs-down-alt text-red' %> paid_icon" title="<%= installment.paid? ? t("models.installment.#{installment.launch_type}.paid") : t("models.installment.#{installment.launch_type}.not_paid") %>"></i>
          </div>
          <div class='clearfix'></div>
        <% end %>
        <hr class='dashboard-hr-account'></hr>
      <% end %>
      <% sum_of_installments = Installment.sum_of_values(@installments) %>
      <h4 class='text-right <%= sum_of_installments > 0 ? 'text-green' : 'text-red' %>'><%= number_to_currency(sum_of_installments) %></h4>
    <% else %>
      Não há lançamentos nesse período
    <% end %>
  </div>
</div>

app/views/installments/_list_report.html.erb
<div class='box'>
  <div class='box-header'>
    <div class='title'>
      <i class='icon-usd'></i>
      <%= t('activerecord.models.launch.other') %>
    </div>
    <div class='actions'>
        <%= link_to "<i class='icon-file-text'></i>".html_safe, home_report_path(format: :csv), class: 'btn btn-primary' %>
        <%= link_to "<i class='icon-plus'></i>".html_safe, new_launch_path, class: 'btn btn-success' %>
    </div>
  </div>
  <div class='box-content'>
    <% if @installments.present? %>
      <% @installments.each do |installment| %>
        <%= link_to installment do %>
          <div class='list_installment_wrapper'>
            <i class="<%= installment.income? ? 'icon-arrow-up text-green' : 'icon-arrow-down text-red' %> launch_type_icon hidden-xs"></i>
            <div class='col-sm-8 col-xs-6'>
              <h4><%= format_title_recurrence(installment) %></h4>
              <h6 style="color: <%= installment.category.try(:color) %>"><%= installment.category.try(:title) %></h6>  
            </div>
            <div class='col-sm-4 col-xs-6'>
              <h4 class='text-right <%= installment.income? ? 'text-green' : 'text-red' %>'><%= number_to_currency(installment.value) %></h4>
              <h6 class='text-right'><%= l(installment.date, format: :date_picker) %></h6>
            </div>
            <i class="<%= installment.paid? ? 'icon-thumbs-up-alt text-green' : 'icon-thumbs-down-alt text-red' %> paid_icon" title="<%= installment.paid? ? t("models.installment.#{installment.launch_type}.paid") : t("models.installment.#{installment.launch_type}.not_paid") %>"></i>
          </div>
          <div class='clearfix'></div>
        <% end %>
        <hr class='report-hr-account'></hr>
      <% end %>
      <% sum_of_installments = Installment.sum_of_values(@installments) %>
      <h4 class='text-right <%= sum_of_installments > 0 ? 'text-green' : 'text-red' %>'><%= number_to_currency(sum_of_installments) %></h4>
    <% else %>
      Não há lançamentos nesse período
    <% end %>
  </div>
</div>

app/views/installments/cancel.js.erb
$('#main_modal .modal-content .modal-body').html("<%= escape_javascript(render(partial: 'cancel_options', locals: {installment: @installment})) %>");
$('#main_modal').modal('show');

app/views/installments/edit.html.erb
<%= render 'header' %>

<%= render 'form' %>

<%= link_to t('helpers.links.show'), @installment %> |
<%= link_to t('helpers.links.back'), installments_path %>

app/views/installments/index.html.erb
<%= render 'header' %>

<%= render 'installments/list' %>

<br>

<%#= link_to t('helpers.titles.new', model: t("activerecord.models.installment.one")), new_installment_path %>

app/views/installments/new.html.erb
<%= render 'header' %>

<%= render 'form' %>

<%= link_to t('helpers.links.back'), installments_path %>

app/views/installments/show.html.erb
<%= render 'header' %>

<div class='row'>
  <div class='col-sm-12'>
    <div class='box bordered-box green-border'>
      <div class='box-header green-background'>
        <div class='title'>
          <%= t('helpers.show') %>
        </div>
      </div>
      <div class='box-content box-double-padding'>

        <p>
          <strong><%= Installment.human_attribute_name("value") %>:</strong>
          <%= number_to_currency(@installment.value) %>
        </p>

        <p>
          <strong><%= Installment.human_attribute_name("date") %>:</strong>
          <%= l(@installment.date, format: :date_picker) %>
        </p>

        <p>
          <strong><%= Installment.human_attribute_name("paid") %>:</strong>
          <%= human_boolean(@installment.paid) %>
        </p>

        <p>
          <strong><%= Installment.human_attribute_name("number_installment") %>:</strong>
          <%= @installment.number_installment %> / <%= @installment.launch.amount_installment %>
        </p>

        <p>
          <strong><%= Installment.human_attribute_name("launch") %>:</strong>
          <%= @installment.launch.title %>
        </p>
        <p>
          <strong><%= Launch.human_attribute_name("proof") %>:</strong>
          <% if @installment.proof.present? %>
            <%= image_tag @installment.proof.url %>
          <% elsif @installment.launch.proof.present? %>
            <%= image_tag @installment.launch.proof.url %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>

<%= link_to t('helpers.titles.edit', model: t("activerecord.models.installment.one")), edit_installment_path(@installment) %> |

<% if @installment.launch.not_recurrence? %>
  <%= link_to t('helpers.titles.delete', model: t("activerecord.models.installment.one")), installment_path(@installment, cancel_this: true), method: :delete, data: { confirm: t('helpers.are_you_sure') } %>
<% else %>
  <%= link_to link_to t('helpers.titles.delete', model: t("activerecord.models.installment.one")), cancel_installment_path(@installment), remote: true %>
<% end %>|

<%= link_to t('helpers.links.back'), root_path %>