config/routes.rb
Rails.application.routes.draw do

  resources :invoices
  namespace :api do
    scope :v1 do
      mount_devise_token_auth_for 'User', at: 'auth'
    end
  end

  devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root to: "home#dashboard"

  get 'home/index'
  get 'home/dashboard'
  get 'home/calendar'
  get 'home/report'
  get 'home/chart'

  resources :users, only: [:index, :show]
  resources :installments do
    get 'cancel', on: :member
  end
  resources :launches do
    get 'apportionment', on: :member
    resources :installments, only: [:index, :edit, :update]
  end
  resources :categories
  resources :accounts
  resources :cards
  resources :groups do
      get 'dashboard', on: :member
    resources :user_groups do
      get 'enable', on: :member
      get 'disable', on: :member
    end
  end
  resources :goals do
    get 'chart', on: :collection
  end
  resources :notifications

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :get_period_installments, only: [:dashboard, :calendar, :chart]
	
  respond_to :html, :json, :js
  	
  def index
  	redirect_to new_user_session_path unless user_signed_in?
  end

  def dashboard
    Launch.generate_recurrence_launches(current_user, @search_period)
    @accounts = policy_scope(Account)
    @cards = policy_scope(Card)

    respond_with(@installments) do |format|
      format.csv { send_data @installments.to_csv, filename: "installments-#{Date.today}.csv" }
    end
  end

  def calendar

    respond_with(@installments)
  end

  def report
    @installments = policy_scope(Installment)
    @installments = @installments.search(params)

    respond_with(@installments) do |format|
      format.csv { send_data @installments.to_csv, filename: "installments-#{Date.today}.csv" }
    end
  end

  def chart
    @total_period = @installments.sum(:value)
    @categories = @installments.select("categories.title, categories.color, sum(value) as total_category")
      .joins(:category).group(:category_id).where(launch_type: 'expense')

    respond_with(@categories)
  end

  private

    def get_period_installments
      @search_period_type = params[:search_period_type] || 'day'
      @search_period = params[:search_period].try(:to_time) || DateTime.now
      @start_date = params[:start_date].try(:to_time) || @search_period.send("beginning_of_#{@search_period_type}")
      @end_date = params[:end_date].try(:to_time) || @search_period.send("end_of_#{@search_period_type}")
      @installments = policy_scope(Installment)
      @installments = @installments.where(date: @start_date..@end_date).order(:date)
    end

end

app/helpers/home_helper.rb
module HomeHelper

	def date_format  
		date_format = l(@search_period, format: :long_day_month_year) if @search_period_type == 'day'
		date_format = l(@search_period, format: :long_month_year) if @search_period_type == 'month'
		date_format = "#{l(@start_date, format: :long_week_month)} à #{l(@end_date, format: :long_week_month)}" if @search_period_type == 'week'
		date_format = "#{l(@start_date.to_date, format: :default)} à #{l(@end_date.to_date, format: :default)}" if @search_period_type == 'period'
		date_format
	end

end

app/views/home/_fullcalendar.html.erb
<div>
  <div id="dashboard_calendar" data-url="<%= home_calendar_url(format: :json) %>"></div>
</div>

app/views/home/_header.html.erb
<div class='page-header page-header-with-buttons'>
  <h1 class='pull-left'>
    <% if action_name.eql?('dashboard') %>
      <i class='icon-dashboard'></i>
      <span><%= t('breadcrumbs.pages.general_view') %></span>
    <% elsif action_name.eql?('calendar') %>
      <i class='icon-calendar'></i>
      <span><%= t('breadcrumbs.pages.calendar') %></span>
    <% elsif action_name.eql?('report') %>
      <i class='icon-list-alt'></i>
      <span><%= t('breadcrumbs.pages.reports') %></span>
    <% elsif action_name.eql?('chart') %>
      <i class='icon-signal'></i>
      <span><%= t('breadcrumbs.pages.charts') %></span>
    <% end %>
  </h1>
</div>

app/views/home/_pie_chart.html.erb
<div class='box'>
  <div class='box-header'>
    <div class='title'>
      <%= t('helpers.charts.expense_pie_chart') %>
    </div>
    <div class='actions'>
      <a class="btn box-remove btn-xs btn-link" href="#"><i class='icon-remove'></i>
      </a>
      
      <a class="btn box-collapse btn-xs btn-link" href="#"><i></i>
      </a>
    </div>
  </div>
  <div class='box-content'>
    <div id='pie_chart' style="height:400px;" data-url="<%= home_chart_url(format: :json) %>"></div>
  </div>
</div>

app/views/home/_search_period_modal.html.erb
<div class="modal fade" id="search_period_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= t('breadcrumbs.pages.search_by_period') %></h4>
      </div>
      <div class="modal-body">
        <div class="container">
			    <div class='col-md-5'>
		        <div class="form-group">
	            <div class='input-group date' id='datetimepicker_from'>
	              <input type='text' class="form-control" />
	              <span class="input-group-addon">
	                <span class="glyphicon glyphicon-calendar"></span>
	              </span>
	            </div>
		        </div>
			    </div>
			    <div class='col-md-5'>
		        <div class="form-group">
	            <div class='input-group date' id='datetimepicker_to'>
	              <input type='text' class="form-control" />
	              <span class="input-group-addon">
	                <span class="glyphicon glyphicon-calendar"></span>
	              </span>
	            </div>
		        </div>
			    </div>
				</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= link_to t('helpers.links.search'), '#', class: 'btn btn-success search_period_link', data: { url: home_dashboard_path, period_type: 'period', context: 'period-chosen' } %>
        <%#= link_to t('helpers.links.search'), home_dashboard_path, class: 'btn btn-success', id: 'search_period_modal_link', remote: true %>
      </div>
    </div>
  </div>
</div>

app/views/home/calendar.html.erb
<%= render 'header' %>

<%= render 'fullcalendar' %>

app/views/home/chart.html.erb
<%= render 'header' %>

<%  
  date_format = l(@search_period, format: :long_day_month_year) if @search_period_type == 'day'
  date_format = l(@search_period, format: :long_month_year) if @search_period_type == 'month'
  date_format = "#{l(@start_date, format: :long_week_month)} à #{l(@end_date, format: :long_week_month)}" if @search_period_type == 'week'
  date_format = "#{l(@start_date, format: :default)} à #{l(@end_date, format: :default)}" if @search_period_type == 'period'
%>

<div class="previous_date" data-value="<%= @search_period.send("beginning_of_#{@search_period_type}") %>"></div>
<div class="next_date" data-value="<%= @search_period.send("end_of_#{@search_period_type}") %>"></div>

<nav class='text-center'>
  <div class='btn-group'>
      <% if @search_period_type != 'period' %>
        <%= link_to "<i class='icon-chevron-left'></i>".html_safe, home_chart_path(search_period_type: @search_period_type, search_period: @search_period - 1.send("#{@search_period_type}")), class: 'btn btn-success btn-md previous' %>
       <% end %>
    <div class='btn-group dropdown'>
      <button class='btn btn-success btn-md dropdown-toggle' data-delay='100' data-hover='dropdown' data-toggle='dropdown'>
        <%= date_format %>
        <span class='caret'></span>
      </button>
      <ul class='dropdown-menu'>
        <li>
          <%= link_to t('datetime.prompts.day'),  home_chart_path(search_period_type: 'day')%>
        </li>
        <li>
          <%= link_to t('datetime.prompts.week'),  home_chart_path(search_period_type: 'week')%>
        </li>
        <li>
          <%= link_to t('datetime.prompts.month'),  home_chart_path(search_period_type: 'month')%>
        </li>
        <li>
          <%= link_to 'Por período', "#", data: {toggle: 'modal', target: '#search_period_modal'} %>
        </li>
      </ul>
    </div>
    <% if @search_period_type != 'period' %>
      <%= link_to "<i class='icon-chevron-right'></i>".html_safe, home_chart_path(search_period_type: @search_period_type, search_period: @search_period + 1.send("#{@search_period_type}")), class: 'btn btn-success btn-md next' %>
     <% end %>
  </div>
</nav>

<%= render 'pie_chart' %>

app/views/home/dashboard.html.erb
<%= render 'header' %>

<div id='period_navigator_dashboard'>
	<%= render 'layouts/period_navigator' %>
</div>

<%= render 'search_period_modal' %>

<div class='row'>
  <div id='accounts_list_dashboard'>
    <%= render 'accounts/list_dashboard' %>
  </div>

  <div id='bills_list_dashboard'>
  	<%= render 'cards/bills_list_dashboard' %>
  </div>
</div>

<div class='row'>
  <div class='col-sm-6' id='installments_list_dashboard'>
    <%= render 'installments/list_dashboard' %>
  </div>

  <div class='col-sm-6' id='pie_chart_dashboard'>
    <%= render 'pie_chart' %>
  </div>

	  <div class='col-sm-12 no_launches' style='display:none;'>
	  	<div class='box'>
			  <div class='box-content'>
				  <i class='icon-3x icon-remove'></i>
				  <h4><%= t('breadcrumbs.pages.no_launches') %></h4>
			  </div>
			</div>
	  </div>

  <!-- <div class='row'> -->
    <div class="col-sm-6">
    </div>

    <div class='col-sm-6' id='fullcalendar_dashboard'>
      <%= render 'fullcalendar' %>
    </div>
  <!-- </div> -->
</div>

app/views/home/dashboard.js.erb
$('div#period_navigator_dashboard').html('<%= escape_javascript( render(partial: "layouts/period_navigator") ) %>');
$('div#accounts_list_dashboard').html('<%= escape_javascript( render(partial: "accounts/list_dashboard") ) %>');
<% if @installments.any? %>
	$('div.no_launches').hide();
	$('div#installments_list_dashboard').html('<%= escape_javascript( render(partial: "installments/list_dashboard") ) %>');
	$('div#pie_chart_dashboard').html('<%= escape_javascript( render "pie_chart" ) %>');
	pie_chart();
<% else %>
	$('div.no_launches').show();
	$('div#installments_list_dashboard').html("");
	$('div#pie_chart_dashboard').html("");
<% end %>
$('div#fullcalendar_dashboard').html('<%= escape_javascript( render("fullcalendar") ) %>');
fullcalendar();

app/views/home/report.html.erb
<%= render 'header' %>

<div class="box">
  <%= form_tag home_report_path, method: 'GET', remote: true, class: "form-inline" do %>
    <div class='col-sm-2'>
      <div class="form-group">
        <div class='input-group date' id='report_start_date'>
          <%= text_field_tag :start_date, params[:start_date], class: "form-control" %>
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>
    </div>
    <div class='col-sm-2'>
      <div class="form-group">
        <div class='input-group date' id='report_end_date'>
        <%= text_field_tag :end_date, params[:end_date], class: "form-control" %>
          <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= text_field_tag :title, params[:title], class: "form-control", placeholder: Launch.human_attribute_name("title") %>
    </div>
    <div class="form-group">
      <%= select_tag :category_id, options_for_select(policy_scope(Category).map{|c| [c.title, c.id]}), class: "form-control", prompt: t('activerecord.models.category.one') %>
    </div>
    <div class="form-group">
      <%= select_tag :group_id, options_for_select(policy_scope(Group).map{|c| [c.title, c.id]}), class: "form-control", prompt: t('activerecord.models.group.one') %>
    </div>
    <div class="form-group">
      <%= select_tag :card_id, options_for_select(policy_scope(Card).map{|c| [c.title, c.id]}), class: "form-control", prompt: t('activerecord.models.card.one') %>
    </div>
    <div class="form-group">
      <%= select_tag :account_id, options_for_select(policy_scope(Account).map{|c| [c.title, c.id]}), class: "form-control", prompt: t('activerecord.models.account.one') %>
    </div>
    <div class="checkbox">
      <%= check_box_tag :expense, true, class: "form-control" %>
      <%= label_tag :expense,  t('activerecord.attributes.launch.launch_types.expense') %>
    </div>
    <div class="checkbox">
      <%= check_box_tag :income, true, class: "form-control" %>
      <%= label_tag :income,  t('activerecord.attributes.launch.launch_types.income') %>
    </div>

    <%= submit_tag 'Buscar', class: 'btn btn-success' %>
  <% end %>
</div>

<hr class="hr-normal"></hr>

<div class='col-sm-12' id='installments_list_report'>
  <%= render 'installments/list_report' %>
</div>

app/views/home/report.js.erb
<% if @installments.any? %>
  $('div.no_launches').hide();
  $('div#installments_list_report').html('<%= escape_javascript( render(partial: "installments/list_report") ) %>');
<% else %>
  $('div.no_launches').show();
  $('div#installments_list_report').html("");
<% end %>